  
tasks:
  - init: playwright install-deps; pip install -r requirements.txt; pip install pytest; npx playwright install; npm install; curl -sSL https://install.python-poetry.org | python3 -
    command: poetry install && pytest

