tasks:
  - name: Install Poetry and Dependencies
    before: Terminal1
    init: |
      # Install Poetry
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="$HOME/.local/bin:$PATH"
      poetry install
      npm install

  - name: Install Python and Pytest
    before: Terminal2
    init: |
      # Ensure pip is up to date
      python3 -m pip install --upgrade pip
      # Install Pytest
      pip install pytest
      npm install

  - name: Install Requirements from requirements.txt
    before: Terminal3
    init: |
      # Ensure pip is up to date
      python3 -m pip install --upgrade pip
      # Install dependencies from requirements.txt
      pip install -r requirements.txt
      npm install

  - name: Playwright Setup and Run Tests
    before: Terminal4
    init: |
      # Install Playwright dependencies
      sudo playwright install-deps
      # Install Poetry
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="$HOME/.local/bin:$PATH"
      # Install Playwright
      npx playwright install
      npm install
    command: |
      # Run tests using Poetry and Playwright
      poetry run pytest
      node playwright-single.js
