tasks:
  - init: playwright install-deps; pip install -r requirements.txt; pip install pytest; playwright install
    command: pytest --numprocesses 3 --headful --browser=firefox --browser=chromium --browser=webkit